### ISSUE TITLE
Feature Request: Implement wide output showing the subnet and gateway.

### ISSUE THREAD

**Issue by adammike** [IBM/staticroute-operator#70]
It would be really nice if the `kubectl get staticroutes -o wide` command returned detailed information on the routes added. I understand that this information can bet obtained with kubectl describe or get, but it would be nice to print it all in a single table that can be used in troubleshooting/validation steps.

Current Behavior: 
```
$ kubectl get staticroutes -o wide
NAME                AGE
on-premise01        183d
on-premise02        183d
on-premise03        183d
```
Desired behavior:
```$ kubectl get staticroutes -o wide
NAME                AGE     NETWORK     GATEWAY
on-premise01        183d    1.2.3.0/24  1.2.3.4
on-premise02        183d    1.2.4.0/24  1.2.3.5
on-premise03        183d    1.2.5.0/24  1.2.3.4
```

**Comment by Tamas-Biro1** [comment]
Implemented in #91, so closing.
