### ISSUE TITLE
Add support for Routing Policies

### ISSUE THREAD

**Issue by AMacedoP** [IBM/staticroute-operator#99]
Hello,

We found this project and works well for configuring static routes on our nodes, but we also need to be able to configure routes in different routing tables and to also configure routing policies. Are there any plans to support them?

Thanks in advance

**Comment by mihivagyok** [comment]
Hi! Thank you for the idea. I see you have already created a PR, we will check it soon and also have some discussion about the routing policies.

Thanks,
Adam

**Comment by AMacedoP** [comment]
Hi @mihivagyok, were you able to check the PR and discuss the Routing Policy feature?
